### ISSUE TITLE
Icons to the left of the text of each button are not displayed.

### ISSUE THREAD

**Issue by condor5** [TheThief/Octoprint_Simple_Filament_Change_Buttons#1]
![image](https://user-images.githubusercontent.com/64713131/88438698-50792200-cdd7-11ea-8487-84c9a9a97491.png)

**Comment by TheThief** [comment]
That's weird - they're just built-in resources, nothing I ship

**Comment by codingcatgirl** [comment]
This might be due to the fact that you set the fa class to the buttons, instead to it's own `<i>` tag, which is not how you're supposed to use fontawesome.

Thas's also where the weird Font on the buttons comes from and alle the other styling issues.

It would be nice if you could implement the fontawesome icons properly so the buttons look how they should :)

**Comment by TheThief** [comment]
Thanks for the info! It's my first time working with an octoprint mod and I copied that from elsewhere. I'll get it fixed!

**Comment by codingcatgirl** [comment]
No worries! I already looked into it and i'm not even sure if there's a way to do it properly right there? You seem to be using a Custom Commands feature from Octoprint and i haven't found anything about it allowing you to use icons at all?

**Comment by t3chguy** [comment]
This is also causing the font to be incorrect when using a theme; see my screenshot where I removed the `fa` class from the first button but not the rest:

![image](https://user-images.githubusercontent.com/2403652/105516278-9b63eb80-5ccd-11eb-9de2-0b245161401d.png)

**Comment by TheThief** [comment]
Fixed in v1.1, hopefully. The font on the button is fixed, which should hopefully fix @condor5's issue also.

If icons still don't work, it'll be because the font of the icon is being overridden by something outside my control - e.g. a styling plugin. Not my fault in that case :)

**Comment by t3chguy** [comment]
Awesome, works perfectly here!

![image](https://user-images.githubusercontent.com/2403652/105924160-a30cf280-6035-11eb-8c49-6ec2f3f127b4.png)

**Comment by condor5** [comment]
Looks good!  Thank you!

![image](https://user-images.githubusercontent.com/64713131/105928901-772d4500-6014-11eb-818f-4d3d1a6a8b60.png)
