### ISSUE TITLE
Buttons not responding

### ISSUE THREAD

**Issue by 3dprintedmac** [TheThief/Octoprint_Simple_Filament_Change_Buttons#2]
I'm running octoprint and buttons do not respond when i click them. I'm running through a Cura Plugin but, i think that shouldn't make a difference...  Any tips to get it working for me? Thanks!

**Comment by TheThief** [comment]
Check the "Terminal" tab - if a button doesn't work, the response from the printer will end up there. I don't know how to make the plugin watch for response.

In my experience, the "resume" command requires multiple presses sometimes.

**Comment by 3dprintedmac** [comment]
Thanks! After some review, I found that apparently my printer, the ender 5 plus, doesn’t respond to the m600 command correctly with its stock firmware, which is super annoying. But means your plug-in works great and my printer is the problem! Thanks for the response!

**Comment by TheThief** [comment]
Unfortunate, but I'm glad you worked it out.
