### ISSUE TITLE
Load button never ends

### ISSUE THREAD

**Issue by TheHolyRoger** [TheThief/Octoprint_Simple_Filament_Change_Buttons#4]
So when i hit load filament on my screen using the professional firmware, it loads a bit then stops and asks to continue the purge.

Load button with this plugin never stops! :) I wasn't even sure which button I was supposed to press to stop the manual load while filament was pouring out of the nozzle :)

**Comment by TheThief** [comment]
Not a problem with this plugin I'm afraid, it just means you need a more complex plugin. This one only invokes the printer's M701 command for load, if the printer doesn't respond correctly to that then there's not much this plugin can do about it.
