### ISSUE TITLE
On the Mini, "Unload" does a filament change

### ISSUE THREAD

**Issue by coaxial** [TheThief/Octoprint_Simple_Filament_Change_Buttons#5]
Rather than simply unloading the filament, it does a filament change; i.e. after unloading, it start the loading process.

Octopi 1.8.1 with Mini 4.3.4 firmware.

**Comment by TheThief** [comment]
You should open that as an issue against the Mini firmware instead. This plugin simply issues the M702 command, it's up to the firmware to respond correctly.

You can verify by issuing the M702 command from the console in Octopi

**Comment by coaxial** [comment]
I think it might be this bug: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1448. Thanks for the quick answer, closing.

**Comment by TheThief** [comment]
That does seem the likely culprit. Hope they can get it fixed for you
